#DB  properties

# main  8080, match 8081, batch 8082
server.port=8080

# WebSocket CORS (Local Host)
localhost=${FRONTEND_ORIGIN:http://localhost:3000}

match.server.url=${MATCH_SERVER_URL:http://localhost:8081}

spring.datasource.url=${MAIN_DB_URL:jdbc:postgresql://localhost:5432/stodb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update

spring.jackson.serialization.write-dates-as-timestamps=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true


logging.level.org.hibernate.orm.jdbc.bind=TRACE


spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.type=simple


# JWT
jwt.secret=${JWT_SECRET:}
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION:3600000}

springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.api-docs.path=/api-docs/json

file.path=${FILE_PATH:./files}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Blockchain
blockchain.issuer-private-key=${BLOCKCHAIN_PRIVATE_KEY:}
blockchain.wallet-encryption-key=${BLOCKCHAIN_WALLET_ENCRYPTION_KEY:}
blockchain.rpc-url=${BLOCKCHAIN_RPC_URL:}

# Gemini AI
gemini.api.url=https://generativelanguage.googleapis.com
gemini.api.key=${GEMINI_API_KEY:}

# Naver News API
naver.api.client-id=${NAVER_CLIENT_ID:}
naver.api.client-secret=${NAVER_CLIENT_SECRET:}
naver.api.news-url=https://openapi.naver.com/v1/search/news.json
