# ?? ??
server.port=8080

# CORS
localhost=${PROD_FRONTEND_ORIGIN:https://sto.shinhanacademy.co.kr}
match.server.url=${DOCKER_MATCH_SERVER_URL:http://app-match:8081}

# DB
spring.datasource.url=${DOCKER_DB_URL:jdbc:postgresql://postgres:5432/stodb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

logging.level.org.hibernate.orm.jdbc.bind=TRACE

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379

# JWT
jwt.secret=${JWT_SECRET:}
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION:3600000}

# Swagger
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.api-docs.path=/api-docs/json

# ?? ??
file.path=${DOCKER_FILE_PATH:/app/files}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Blockchain
blockchain.wallet-encryption-key=${BLOCKCHAIN_WALLET_ENCRYPTION_KEY:}

spring.jackson.time-zone=Asia/Seoul
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

# Gemini AI
gemini.api.url=https://generativelanguage.googleapis.com
gemini.api.key=${GEMINI_API_KEY:}

# Naver News API
naver.api.client-id=${NAVER_CLIENT_ID:}
naver.api.client-secret=${NAVER_CLIENT_SECRET:}
naver.api.news-url=https://openapi.naver.com/v1/search/news.json
