spring.batch.job.enabled=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true


logging.level.org.hibernate.orm.jdbc.bind=TRACE

# MyBatis XML ?? ?? ??
mybatis.mapper-locations=classpath:mapper/**/*.xml
# MyBatis snake -> camel ??
mybatis.configuration.map-underscore-to-camel-case=true

# spring.data.redis.host=localhost
# spring.data.redis.port=6379