



server.port=8081

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true


logging.level.org.hibernate.orm.jdbc.bind=TRACE

# MyBatis XML
mybatis.mapper-locations=classpath:mapper/**/*.xml
# MyBatis snake -> camel
mybatis.configuration.map-underscore-to-camel-case=true

# spring.data.redis.host=localhost
# spring.data.redis.port=6379

springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.api-docs.path=/api-docs/json